name: Lighthouse Performance Audit

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --no-audit --no-fund

      - name: Build Project
        run: npm run build

      - name: Run Lighthouse CI
        run: npm run lighthouse:ci
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30

      - name: Comment PR with Results
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('.lighthouseci/manifest.json', 'utf8'));
            const scores = results[0].summary;
            
            const comment = `## 🏆 Lighthouse Performance Results
            
            | Category | Score |
            |----------|-------|
            | 🚀 Performance | ${scores.performance * 100}/100 |
            | ♿ Accessibility | ${scores.accessibility * 100}/100 |
            | ✅ Best Practices | ${scores['best-practices'] * 100}/100 |
            | 🔍 SEO | ${scores.seo * 100}/100 |
            
            [View Full Report](https://googlechrome.github.io/lighthouse/viewer/)`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  performance-budget:
    name: Performance Budget Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --no-audit --no-fund

      - name: Build Project
        run: npm run build

      - name: Start Preview Server
        run: npm run preview &
        
      - name: Wait for Server
        run: sleep 5

      - name: Install Lighthouse CLI
        run: npm install -g lighthouse

      - name: Check Performance Budget
        run: |
          lighthouse http://localhost:4173 \
            --budget-path=./performance-budget.json \
            --output=json \
            --output-path=./budget-results.json \
            --chrome-flags="--headless"

      - name: Upload Budget Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: budget-results
          path: budget-results.json
          retention-days: 30
